### ISSUE TITLE
Exception in thread WebSocketClient: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [vkruoso/robot-watchdog#2]
Getting this exception:

![image](https://cloud.githubusercontent.com/assets/5635462/15957765/8ca37e1c-2ef1-11e6-97b2-1a0af8c6bca9.png)

``` cmd
UTF-8 Test                                                            .Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\users\me\envs\portal_tests\lib\site-packages\ws4py\websocket.py", line 506, in run
    if not self.once():
  File "c:\users\me\envs\portal_tests\lib\site-packages\DDPClient.py", line 53, in once
    return super(DDPSocket, self).once()
  File "c:\users\me\envs\portal_tests\lib\site-packages\ws4py\websocket.py", line 388, in once
    if not self.process(b):
  File "c:\users\me\envs\portal_tests\lib\site-packages\ws4py\websocket.py", line 458, in process
    self.received_message(s.message)
  File "c:\users\me\envs\portal_tests\lib\site-packages\DDPClient.py", line 41, in received_message
    self.emit('received_message', data)
  File "c:\users\me\envs\portal_tests\lib\site-packages\pyee\__init__.py", line 117, in emit
    f(*args, **kwargs)
  File "c:\users\me\envs\portal_tests\lib\site-packages\DDPClient.py", line 187, in received_message
    callback(data.get('error'), data.get('result'))
  File "c:\users\me\envs\portal_tests\robotwatchdog.py", line 57, in handle_run_call
    self.run = result.get('run', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Tset-Noitamotua** [comment]
My fault. I didn´t start meteor in `robot-dashboard` folder.

For those who run into similar issue, check out '[Getting Started](https://github.com/Tset-Noitamotua/robot-dashboard#getting-started-windows-7)' section.

**Comment by vkruoso** [comment]
I think that is really a bug. When no server is there to receive results, we should fail more gracefully. In the end we should respect some sort of timeout before letting the test itself finish.
